#!/bin/bash

#la date du jour

d=$(date +%d%m%y)

#prefix pour le nom du fichier (imck-db_)

pref=imck-db_

#concatenation prefix et date

fn=$pref$d

#lacement du mysqldump et persistence dans un fichier

mysqldump bhima -u root -pHISCongo2013 --skip-triggers --ignore-table=bhima.sym_* > ~/$fn.sql

#deplacement dans le dossier personnel

cd

#nom du fichier compresser

fn_comp=$fn.tar.gz

#lancement compression

tar czvf $fn_comp $fn.sql

#deplacement fichier dans le dossier de synchronisation dropbox

mv $fn_comp ~/Dropbox/$fn_comp

echo backup termine avec succes!
